// Code generated by goctl. DO NOT EDIT.
package types

type HelloReq struct {
	Name string `json:"name,optional"`
}

type HelloResp struct {
	Message string `json:"message"`
}

type WalletAuthReq struct {
	Signature  string `json:"signature"`
	Message    string `json:"message"`
	InviteCode string `json:"invite_code"`
}

type WalletAuthNotSignReq struct {
	Address      string `json:"address"`
	ReferralCode string `json:"referral_code"`
}

type WalletAuthData struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
	WataReward   int    `json:"wata_reward"`
	Role         string `json:"role"`
}

type WalletAuthResp struct {
	Message string         `json:"message"`
	Data    WalletAuthData `json:"data"`
}

type ErrorResp struct {
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}
