// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"wata-bot-BE/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/hello",
				Handler: HelloHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/wallet",
				Handler: WalletAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/wallet-not-sign",
				Handler: WalletAuthNotSignHandler(serverCtx),
			},
		},
	)
}
